#!/usr/bin/env bash
#
# Installs the json2bean CLI for terminal-wide use.
#
#   build fat jar -> copy to ~/.local/share/json2bean -> launcher in ~/.local/bin
#   -> ensure ~/.local/bin is on PATH
#
# Usage:  ./scripts/install-cli.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
SHARE_DIR="${HOME}/.local/share/json2bean"
BIN_DIR="${HOME}/.local/bin"
LAUNCHER="${BIN_DIR}/json2bean"
JAR_DEST="${SHARE_DIR}/json2bean.jar"

echo "==> Checking Java"
if ! command -v java >/dev/null 2>&1; then
  echo "ERROR: 'java' not found on PATH. Install a JDK 17+ first." >&2
  exit 1
fi

echo "==> Building the CLI fat jar (./gradlew :cli:shadowJar)"
"${REPO_ROOT}/gradlew" -p "${REPO_ROOT}" :cli:shadowJar --console=plain -q

# Locate the freshly built fat jar (the '-all.jar' classifier).
JAR_SRC="$(ls -t "${REPO_ROOT}"/cli/build/libs/json2bean-*-all.jar 2>/dev/null | head -1 || true)"
if [[ -z "${JAR_SRC}" ]]; then
  echo "ERROR: could not find cli/build/libs/json2bean-*-all.jar after build." >&2
  exit 1
fi
echo "    built: ${JAR_SRC}"

echo "==> Installing jar to ${JAR_DEST}"
mkdir -p "${SHARE_DIR}" "${BIN_DIR}"
cp -f "${JAR_SRC}" "${JAR_DEST}"

echo "==> Writing launcher ${LAUNCHER}"
cat > "${LAUNCHER}" <<EOF
#!/usr/bin/env bash
# json2bean CLI launcher (generated by scripts/install-cli.sh)
exec java -jar "${JAR_DEST}" "\$@"
EOF
chmod +x "${LAUNCHER}"

# Ensure ~/.local/bin is on PATH for future shells.
ensure_path() {
  local rc="$1"
  [[ -f "${rc}" ]] || return 0
  if ! grep -q '# json2bean CLI' "${rc}" 2>/dev/null; then
    {
      echo ''
      echo '# json2bean CLI'
      echo 'export PATH="$HOME/.local/bin:$PATH"'
    } >> "${rc}"
    echo "    added ~/.local/bin to PATH in ${rc}"
  fi
}

case ":${PATH}:" in
  *":${BIN_DIR}:"*)
    echo "==> ${BIN_DIR} already on PATH"
    ;;
  *)
    echo "==> Adding ${BIN_DIR} to PATH"
    # Cover zsh and bash; harmless if a file is absent.
    ensure_path "${HOME}/.zshrc"
    ensure_path "${HOME}/.bashrc"
    echo "    open a NEW terminal (or 'source ~/.zshrc') to pick it up"
    ;;
esac

echo ""
echo "Done. Try:  json2bean --help"
echo "(If 'json2bean' isn't found, open a new terminal first.)"
